<?php

declare (strict_types = 1);

namespace App\Helpers;

class EnumHelper extends ListHelper
{
    const
    NAMES = ['John', 'Jane', 'Jack', 'Jill', 'Jake', 'Jade', 'Jeff', 'Jess', 'Joel', 'Josh', 'Jose', 'Jude', 'June', 'Jean'],
    ROLE = [null,'Webmaster', 'Administrator', 'Director', 'Manager', 'Officer'],
    ACCESS_RIGHT = ['NONE', 'ALL', 'ADD', 'VIEW', 'EDIT', 'DELETE', 'GRANT', 'REVOKE', 'READ_ONLY', 'WRITE_ONLY'],
    ACTION = [null, 'INSERT', 'SELECT', 'UPDATE', 'DELETE', 'SIGN_UP', 'SIGN_IN', 'SIGN_OUT'],
    GENDER = [null, 'Male', 'Female', 'Non-Binary'],
    SEX = [null, 'M', 'F', 'N_B'],
    SEX_MAP = ['N/A' => null, 'M' => 'Male', 'F' => 'Female', 'N_B' => 'Non-Binary'],
    TITLE = [null, 'Dr.', 'Esq.', 'Hon.', 'Jr.', 'Mr.', 'Mrs.', 'Ms.', 'Msgr.', 'Prof.', 'Rev.', 'Sr.', 'St.'],
    PRONOUN = [null, 'I', 'You', 'He', 'She', 'It', 'We', 'They', 'Me', 'Him', 'Her', 'Us', 'Them'],
    MARITAL_STATUS = [null, 'Single', 'Married', 'Separated', 'Divorced', 'Widowed'],
    RELIGION = [null, 'Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Sikhism', 'Taoism', 'Judaism', 'Confucianism', 'Bahá&apos;í', 'Shinto', 'Jainism', 'Zoroastrianism', 'Others'],
    RACE = [null, 'White/Caucasian', 'Mongoloid/Asian', 'Negroid/Black', 'Australoid'],
    CONTINENT = [null, 'Africa', 'North/South America', 'Antarctica', 'Asia', 'Australia', 'Europe', 'Oceania'],
    MONTH = [null, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    DAY = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    MONTH_ = [null, 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
    DAY_ = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'],
    NOTICE_PERIOD = [null, 'Immediately', '3 days', '1 Week', '2 weeks', '3 weeks', '4 weeks', '1+ month', '2+ months', '3+ months', '6+ months'],
    SEASON = [null, 'Spring', 'Summer', 'Autumn (Fall)', 'Winter'],
    AGE_GROUP = [null, '0 – 12  (Adolescent)', '13 – 19  (Teenager)', '20 – 49  (Adult)', '50 – 74  (Senior)', '75 – above  (Elder)'],
    AGE_GROUP_MAP = [null, 'Adolescent' => '0 – 12', 'Teenager' => '13 – 19', 'Adult' => '20 – 49', 'Senior' => '50 – 74', 'Elder' => '75 – above'],
    TXN_TYPE = [null, 'Credit', 'Debit'],
    TXN_TYPE_MAP = ['N/A' => null, 'CR' => 'Credit', 'DR' => 'Debit'],
    TXN_STATUS = ['Pending', 'Approved', 'Declined', 'Critical'],
    PAY_MODE = [null, 'ATM/Quick Teller', 'Bank Transfer', 'Cash Deposit', 'Internet Banking', 'Mobile Transfer', 'Point-Of-Sale (POS)', 'SMS/USSD Code', 'Web Checkout'],
    PAY_ISP = [null, 'Paypal', 'Interswitch', 'Stripe', 'Remita', 'Paystack', 'Flutterwave', 'VoguePay', 'CashEnvoy'],
    CARD_TYPE = ['AMEX', 'APPLE PAY', 'VERVE', 'VISA', 'MASTERCARD'],
    STATUS = ['Unverified', 'Verified', 'Disabled', 'Enabled', 'Inactive', 'Active'],
    ENTITY = [
        null,
        'ADMIN', 'USER',
        'FAMILY', 'FRIEND',
        'EMPLOYER', 'EMPLOYEE', 'CUSTOMER/CLIENT', 'ENQUIRER', 'VISITOR',
        'STAFF', 'STUDENT', 'PUPIL',
        'PARENT/GUARDIAN', 'SPONSOR', 'NEXT OF KIN',
        'APPLICANT', 'GUARANTOR',
        'CANDIDATE', 'REFERER', 'REFEREE',
        'DOCTOR', 'NURSE', 'PHARMACIST/CHEMIST', 'PATIENT',
    ],
    SCHEDULE = [
        null,
        'Full-time',
        'Part-time',
        'Contract',
        'Intern',
        'Apprentice',
        'Seasonal',
        'On-site',
        'Off-site',
        'Hybrid',
    ],
    BANKS_NG = [
        null,
        'Access Bank',
        'Citi Bank',
        'Diamond Bank (Access)',
        'Ecobank', 'FCMB',
        'Fidelity Bank', 'FirstBank',
        'GTBank',
        'Heritage Bank',
        'Jaiz Bank', 'Jubilee Bank',
        'Keystone Bank',
        'Mainstreet Bank',
        'Skye Bank (Polaris)', 'Stanbic IBTC', 'Standard Chartered Bank', 'Sterling Bank', 'Suntrust Bank',
        'UBA', 'Union Bank', 'Unity Bank',
        'WEMA Bank',
        'Zenith Bank',
    ],
    STATES_NG = [
        null,
        'Abia', 'Abuja', 'Adamawa', 'Akwa Ibom', 'Anambra',
        'Bauchi', 'Bayelsa', 'Benue', 'Borno',
        'Cross River',
        'Delta',
        'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
        'Gombe',
        'Imo',
        'Jigawa',
        'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
        'Lagos',
        'Nasarawa', 'Niger',
        'Ogun', 'Ondo', 'Osun', 'Oyo',
        'Plateau',
        'Rivers',
        'Sokoto',
        'Taraba',
        'Yobe',
        'Zamfara',
    ],
    DEGREE = [
        null,
        'WASSCE' => 'West African Secondary School Certificate Examination',
        'GCE ' => 'General Certificate of Education',
        'OND' => 'Ordinary National Diploma',
        'NHD' => 'Higher National Diploma',
        'LLB' => 'Bachelor of Law',
        'B.Sc' => 'Bachelor of Science',
        'PGD' => 'Post Graduate Diploma',
        'PGDE' => 'Post Graduate Diploma in Education',
        'M.Sc' => 'Master of Science',
        'Ph.D' => 'Doctor of Philosophy',
    ],
    FILE = [
        null,
        'Affidavit',
        'Age Declaration',
        'Audio',
        'Award',
        'Birth Certificate',
        'Certificate',
        'Certificate of Occupancy (C of O)',
        'CV/R&eacute;sum&eacute;',
        'Document',
        'Driver&apos;s License',
        'Hospital Card (HMO)',
        'ID Card',
        'Image',
        'Int&apos;l Passport',
        'Marriage Certificate',
        'Medical Report',
        'National ID Card',
        'Particulars',
        'Photograph',
        'Receipt/Teller',
        'Resident Permit',
        'Staff ID Card',
        'Statement',
        'Student ID Card',
        'Utility Bill',
        'Video',
        'Voter&apos;s Card',
        'Work Permit',
    ],
    COUNTRY = [
        null,
        'AFG' => 'Afghanistan',
        'ALA' => 'Åland Islands',
        'ALB' => 'Albania',
        'DZA' => 'Algeria',
        'ASM' => 'American Samoa',
        'AND' => 'Andorra',
        'AGO' => 'Angola',
        'AIA' => 'Anguilla',
        'ATA' => 'Antarctica',
        'ATG' => 'Antigua and Barbuda',
        'ARG' => 'Argentina',
        'ARM' => 'Armenia',
        'ABW' => 'Aruba',
        'AUS' => 'Australia',
        'AUT' => 'Austria',
        'AZE' => 'Azerbaijan',
        'BHS' => 'Bahamas',
        'BHR' => 'Bahrain',
        'BGD' => 'Bangladesh',

        'BRB' => 'Barbados',
        'BLR' => 'Belarus',
        'BEL' => 'Belgium',
        'BLZ' => 'Belize',
        'BEN' => 'Benin',
        'BMU' => 'Bermuda',
        'BTN' => 'Bhutan',
        'BOL' => 'Bolivia, Plurinational State of..',
        'BES' => 'Bonaire, Sint Eustatius and Saba',
        'BIH' => 'Bosnia and Herzegovina',
        'BWA' => 'Botswana',
        'BVT' => 'Bouvet Island',
        'BRA' => 'Brazil',
        'IOT' => 'British Indian Ocean Territory',
        'BRN' => 'Brunei Darussalam',
        'BGR' => 'Bulgaria',
        'BFA' => 'Burkina Faso',
        'BDI' => 'Burundi',
        'KHM' => 'Cambodia',
        'CMR' => 'Cameroon',
        'CAN' => 'Canada',
        'CPV' => 'Cape Verde',
        'CYM' => 'Cayman Islands',
        'CAF' => 'Central African Republic',
        'TCD' => 'Chad',
        'CHL' => 'Chile',
        'CHN' => 'China',
        'CXR' => 'Christmas Island',
        'CCK' => 'Cocos (Keeling) Islands',
        'COL' => 'Colombia',
        'COM' => 'Comoros',
        'COG' => 'Congo',
        'COD' => 'Congo, the Democratic Republic of the',
        'COK' => 'Cook Islands',
        'CRI' => 'Costa Rica',
        'CIV' => 'Côte d&apos;Ivoire',
        'HRV' => 'Croatia',
        'CUB' => 'Cuba',
        'CUW' => 'Curaçao',
        'CYP' => 'Cyprus',
        'CZE' => 'Czech Republic',
        'DNK' => 'Denmark',
        'DJI' => 'Djibouti',
        'DMA' => 'Dominica',
        'DOM' => 'Dominican Republic',
        'ECU' => 'Ecuador',
        'EGY' => 'Egypt',
        'SLV' => 'El Salvador',
        'GNQ' => 'Equatorial Guinea',
        'ERI' => 'Eritrea',
        'EST' => 'Estonia',
        'ETH' => 'Ethiopia',
        'FLK' => 'Falkland Islands (Malvinas)',
        'FRO' => 'Faroe Islands',
        'FJI' => 'Fiji',
        'FIN' => 'Finland',
        'FRA' => 'France',
        'GUF' => 'French Guiana',
        'PYF' => 'French Polynesia',
        'ATF' => 'French Southern Territories',
        'GAB' => 'Gabon',
        'GMB' => 'Gambia',
        'GEO' => 'Georgia',
        'DEU' => 'Germany',
        'GHA' => 'Ghana',
        'GIB' => 'Gibraltar',
        'GRC' => 'Greece',
        'GRL' => 'Greenland',
        'GRD' => 'Grenada',
        'GLP' => 'Guadeloupe',
        'GUM' => 'Guam',
        'GTM' => 'Guatemala',
        'GGY' => 'Guernsey',
        'GIN' => 'Guinea',
        'GNB' => 'Guinea-Bissau',
        'GUY' => 'Guyana',
        'HTI' => 'Haiti',
        'HMD' => 'Heard Island and McDonald Islands',
        'VAT' => 'Holy See (Vatican City State)',
        'HND' => 'Honduras',
        'HKG' => 'Hong Kong',
        'HUN' => 'Hungary',
        'ISL' => 'Iceland',
        'IND' => 'India',
        'IDN' => 'Indonesia',
        'IRN' => 'Iran, Islamic Republic of..',
        'IRQ' => 'Iraq',
        'IRL' => 'Ireland',
        'IMN' => 'Isle of Man',
        'ISR' => 'Israel',
        'ITA' => 'Italy',
        'JAM' => 'Jamaica',
        'JPN' => 'Japan',
        'JEY' => 'Jersey',
        'JOR' => 'Jordan',
        'KAZ' => 'Kazakhstan',
        'KEN' => 'Kenya',
        'KIR' => 'Kiribati',
        'PRK' => 'Korea, Democratic People&apos;s Republic of..',
        'KOR' => 'Korea, Republic of..',
        'KWT' => 'Kuwait',
        'KGZ' => 'Kyrgyzstan',
        'LAO' => 'Lao People&apos;s Democratic Republic',
        'LVA' => 'Latvia',
        'LBN' => 'Lebanon',
        'LSO' => 'Lesotho',
        'LBR' => 'Liberia',
        'LBY' => 'Libya',
        'LIE' => 'Liechtenstein',
        'LTU' => 'Lithuania',
        'LUX' => 'Luxembourg',
        'MAC' => 'Macao',
        'MKD' => 'Macedonia, the former Yugoslav Republic of..',
        'MDG' => 'Madagascar',
        'MWI' => 'Malawi',
        'MYS' => 'Malaysia',
        'MDV' => 'Maldives',
        'MLI' => 'Mali',
        'MLT' => 'Malta',
        'MHL' => 'Marshall Islands',
        'MTQ' => 'Martinique',
        'MRT' => 'Mauritania',
        'MUS' => 'Mauritius',
        'MYT' => 'Mayotte',
        'MEX' => 'Mexico',
        'FSM' => 'Micronesia, Federated States of..',
        'MDA' => 'Moldova, Republic of..',
        'MCO' => 'Monaco',
        'MNG' => 'Mongolia',
        'MNE' => 'Montenegro',
        'MSR' => 'Montserrat',
        'MAR' => 'Morocco',
        'MOZ' => 'Mozambique',
        'MMR' => 'Myanmar',
        'NAM' => 'Namibia',
        'NRU' => 'Nauru',
        'NPL' => 'Nepal',
        'NLD' => 'Netherlands',
        'NCL' => 'New Caledonia',
        'NZL' => 'New Zealand',
        'NIC' => 'Nicaragua',
        'NER' => 'Niger',
        'NGA' => 'Nigeria',
        'NIU' => 'Niue',
        'NFK' => 'Norfolk Island',
        'MNP' => 'Northern Mariana Islands',
        'NOR' => 'Norway',
        'OMN' => 'Oman',
        'PAK' => 'Pakistan',
        'PLW' => 'Palau',
        'PSE' => 'Palestinian Territory, Occupied',
        'PAN' => 'Panama',
        'PNG' => 'Papua New Guinea',
        'PRY' => 'Paraguay',
        'PER' => 'Peru',
        'PHL' => 'Philippines',
        'PCN' => 'Pitcairn',
        'POL' => 'Poland',
        'PRT' => 'Portugal',
        'PRI' => 'Puerto Rico',
        'QAT' => 'Qatar',
        'REU' => 'Réunion',
        'ROU' => 'Romania',
        'RUS' => 'Russian Federation',
        'RWA' => 'Rwanda',
        'BLM' => 'Saint Barthélemy',
        'SHN' => 'Saint Helena, Ascension and Tristan da Cunha',
        'KNA' => 'Saint Kitts and Nevis',
        'LCA' => 'Saint Lucia',
        'MAF' => 'Saint Martin (French part)',
        'SPM' => 'Saint Pierre and Miquelon',
        'VCT' => 'Saint Vincent and the Grenadines',
        'WSM' => 'Samoa',
        'SMR' => 'San Marino',
        'STP' => 'Sao Tome and Principe',
        'SAU' => 'Saudi Arabia',
        'SEN' => 'Senegal',
        'SRB' => 'Serbia',
        'SYC' => 'Seychelles',
        'SLE' => 'Sierra Leone',
        'SGP' => 'Singapore',
        'SXM' => 'Sint Maarten (Dutch part)',
        'SVK' => 'Slovakia',
        'SVN' => 'Slovenia',
        'SLB' => 'Solomon Islands',
        'SOM' => 'Somalia',
        'ZAF' => 'South Africa',
        'SGS' => 'South Georgia and the South Sandwich Islands',
        'SSD' => 'South Sudan',
        'ESP' => 'Spain',
        'LKA' => 'Sri Lanka',
        'SDN' => 'Sudan',
        'SUR' => 'Suriname',
        'SJM' => 'Svalbard and Jan Mayen',
        'SWZ' => 'Swaziland',
        'SWE' => 'Sweden',
        'CHE' => 'Switzerland',
        'SYR' => 'Syrian Arab Republic',
        'TWN' => 'Taiwan, Province of China',
        'TJK' => 'Tajikistan',
        'TZA' => 'Tanzania, United Republic of..',
        'THA' => 'Thailand',
        'TLS' => 'Timor-Leste',
        'TGO' => 'Togo',
        'TKL' => 'Tokelau',
        'TON' => 'Tonga',
        'TTO' => 'Trinidad and Tobago',
        'TUN' => 'Tunisia',
        'TUR' => 'Turkey',
        'TKM' => 'Turkmenistan',
        'TCA' => 'Turks and Caicos Islands',
        'TUV' => 'Tuvalu',
        'UGA' => 'Uganda',
        'UKR' => 'Ukraine',
        'ARE' => 'United Arab Emirates',
        'GBR' => 'United Kingdom',
        'USA' => 'United States',
        'UMI' => 'United States Minor Outlying Islands',
        'URY' => 'Uruguay',
        'UZB' => 'Uzbekistan',
        'VUT' => 'Vanuatu',
        'VEN' => 'Venezuela, Bolivarian Republic of..',
        'VNM' => 'Viet Nam',
        'VGB' => 'Virgin Islands, British',
        'VIR' => 'Virgin Islands, U.S.',
        'WLF' => 'Wallis and Futuna',
        'ESH' => 'Western Sahara',
        'YEM' => 'Yemen',
        'ZMB' => 'Zambia',
        'ZWE' => 'Zimbabwe',
    ];
}
